sensor:
  - platform: nordpool
    region: "{{ region | default('SE4') }}"
    currency: "{{ currency | default('SEK') }}"
    price_type: "kWh"
    low_price_cutoff: 0.1
    precision: 3
    VAT: true

automation:
  - alias: "Adjust thermostat based on Nordpool price"
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      - condition: numeric_state
        entity_id: sensor.nordpool_kwh_sek_se4
        below: 0.1
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.your_thermostat
        data:
          temperature: 21
