# Define variables for Nordpool configuration
nordpool:
  region: "SE4"
  currency: "SEK"

# Include other configuration files
input_text: !include configuration/input_text.yaml
sensor: !include_dir_merge_list sensors/
automation: !include_dir_merge_list automations/

# Include the Nordpool configuration
sensor: !include configuration/nordpool/nordpool.yaml
