homekit:
  filter:
    include_domains:
      - light

automation:
  - alias: "Adjust lighting based on Nordpool price"
    trigger:
      - platform: numeric_state
        entity_id: sensor.nordpool_kwh_sek_se4
        below: 0.05
    action:
      - service: light.turn_on
        target:
          entity_id: light.living_room
  - alias: "Dim lights when price is high"
    trigger:
      - platform: numeric_state
        entity_id: sensor.nordpool_kwh_sek_se4
        above: 0.05
    action:
      - service: light.turn_off
        target:
          entity_id: light.living_room
